bootstrap: firmware-cli: add better error controls and support booting an image
Using kexec, it becomes possible to boot an image loaded into memory.

diff --git a/rootfs/scripts/firmware-cli b/rootfs/scripts/firmware-cli
--- a/rootfs/scripts/firmware-cli
+++ b/rootfs/scripts/firmware-cli
@@ -10,6 +10,7 @@ SERIAL_BAUD=115200
 DOWNLOAD_SAVE=N
 DOWNLOAD_IMAGE_FILE=/tmp/file.tgz
 FLASH_MNT=/flash
+FLASH_MBR=
 FLASH_PART=
 FLASH_CMDLINE=
 FLASH_SIZE=0
@@ -20,6 +21,7 @@ NET_INTR=eth0
 NET_ADDR=
 NET_MASK=
 NET_GWAY=
+NET_OK=
 
 # local proxy configuration
 NET_PROX=N
@@ -158,6 +160,7 @@ do_ask_string() {
 # Prompts the message in "$1" and asks for an IP address for the variable "$2",
 # which will only be accepted between $3 and $4 (if they exists). The
 # variable is updated. Normally returns 0, except when Ctrl-D has been hit (1).
+# '-' alone voids the field.
 do_ask_ip_address() {
   _msg_="$1"; _var_=$2
   _low_=${3:-1.0.0.0} ; _high_=${4:-223.255.255.255}
@@ -167,7 +170,30 @@ do_ask_ip_address() {
     echo -n "${_msg_:+$_msg_ }[$_cur_] ? "
     read _str_
     [ $? -gt 0 ] && { echo "<Abort>"; return 1; }   # Ctrl-D aborts.
-    [ -n "$_str_" ] || return 0   # returns keeps the value
+    [ -z "$_str_" ] && return 0   # returns keeps the value
+    if [ ".$_str_" = ".-" ]; then
+      eval $_var_=
+      return 0
+    elif do_test_dotnum "${_str_}" && [ "${_str_%%.*}" -ge "${_low_%%.*}" ] \
+       && [ "${_str_%%.*}" -le "${_high_%%.*}" ]; then
+      eval $_var_=$_str_
+      return 0
+    fi
+    echo;echo ">>> Address out of range. Please try again or press <Ctrl-D> to abort."
+  done
+}
+
+# same except that the empty adress is not allowed.
+do_ask_non_void_ip_address() {
+  _msg_="$1"; _var_=$2
+  _low_=${3:-1.0.0.0} ; _high_=${4:-223.255.255.255}
+  _cur_="$(eval echo \$$_var_)"
+  _str_=
+  while : ; do
+    echo -n "${_msg_:+$_msg_ }[$_cur_] ? "
+    read _str_
+    [ $? -gt 0 ] && { echo "<Abort>"; return 1; }   # Ctrl-D aborts.
+    [ -z "$_str_" -a -n "$_cur_" ] && return 0   # returns keeps the value if any
     if do_test_dotnum "${_str_}" && [ "${_str_%%.*}" -ge "${_low_%%.*}" ] \
        && [ "${_str_%%.*}" -le "${_high_%%.*}" ]; then
       eval $_var_=$_str_
@@ -210,8 +236,9 @@ do_menu() {
 # this function configures the local network parameters and applies them.
 do_set_local_ip() {
   i="$NET_INTR"; a="$NET_ADDR"; m="$NET_MASK"; g="$NET_GWAY"
+  NET_OK=
   do_ask_string "Ethernet interface (ethX)" NET_INTR && [ -n "$NET_INTR" ] || return 1
-  do_ask_ip_address "$NET_INTR: IP address" NET_ADDR && [ -n "$NET_ADDR" ] || return 1
+  do_ask_non_void_ip_address "$NET_INTR: IP address" NET_ADDR || return 1
   if [ ".$a" != ".$NET_ADDR" ]; then
     # the address has changed, we'll compute the default mask for the user
     a=${NET_ADDR%%.*}
@@ -219,9 +246,9 @@ do_set_local_ip() {
     [ $a -lt 192 ] && NET_MASK="255.255.0.0"
     [ $a -lt 128 ] && NET_MASK="255.0.0.0"
   fi
-  do_ask_ip_address "$NET_INTR: IP mask" NET_MASK 0.0.0.0 255.255.255.255 || return 1
+  do_ask_non_void_ip_address "$NET_INTR: IP mask" NET_MASK 0.0.0.0 255.255.255.255 || return 1
   do_ask_ip_address "$NET_INTR: IP default gateway (- to remove)" NET_GWAY || return 1
-  [ ".$NET_GWAY" = ".-" ] && NET_GWAY=
+  #[ ".$NET_GWAY" = ".-" ] && NET_GWAY=
 
   do_inform "New network parameters for $NET_INTR: $NET_ADDR/$NET_MASK${NET_GWAY:+ gw $NET_GWAY}."
   if do_confirm "These parameters will be applied now"; then
@@ -239,6 +266,7 @@ do_set_local_ip() {
       return 1;
     fi
     do_inform "Network parameters applied successfully."
+    NET_OK=1
   else
     do_inform "Network parameters not applied."
   fi
@@ -269,11 +297,11 @@ do_test_system_partition() {
   fi
 
   partnum=${flash##*[^0-9]}
-  radix=${flash%$partnum}
+  mbr=${flash%$partnum}
   
   if [ -n "$partnum" -a -z "${partnum##[0-9]*}" ]; then
     newpart=$(( $partnum - 1 ))
-    firmware=${radix}${newpart}
+    firmware=${mbr}${newpart}
   else
     do_inform
     do_error "Invalid partition: $flash"
@@ -293,7 +321,20 @@ do_test_system_partition() {
     do_error "$flash cannot be the system partition because $firmware is not the firmware partition."
     return 1
   fi
+
+  mbrdev=${mbr##/dev/}
+  while [ -n "$mbrdev" ] && ! grep  " $mbrdev\$" /proc/partitions; do
+    mbrdev=${mbrdev%?}
+  done
+
+  if [ -z "$mbrdev" ]; then
+    do_inform
+    do_error "MBR not found for device $flash. Please check the device."
+    return 1
+  fi
+
   FIRMWARE_PART=$firmware
+  FLASH_MBR=/dev/$mbrdev
   do_inform "This seems to be the right partition - $flash ($size kB)"
 }
 
@@ -360,7 +401,14 @@ do_menu_format_flash() {
 
 
 # This show the various system images to the user
-do_menu_view_images() {
+do_view_images() {
+  do_inform "-- System image versions --" ; do_inform
+  if [ -s "$DOWNLOAD_IMAGE_FILE" ]; then
+    _ver=$(update-boot-image -n -v -q $DOWNLOAD_IMAGE_FILE) || _ver="invalid image"
+  else
+    _ver=
+  fi
+  do_inform "Pending image version : ${_ver:-none}"
   do_test_system_partition >/dev/null 2>&1 || do_select_flash || return 1
 
   flash="$FLASH_PART"
@@ -377,10 +425,16 @@ do_menu_view_images() {
   [ -r $FLASH_MNT/sys/backup/kernel.ver ] && \
     backup=$(cat $FLASH_MNT/sys/backup/kernel.ver 2>/dev/null)
 
-  do_inform "Active image version : $active"
-  do_inform "Backup image version : $backup"
+  do_inform "Active image version  : $active"
+  do_inform "Backup image version  : $backup"
   umount $FLASH_MNT >/dev/null 2>&1
   do_inform
+  return 0
+}
+
+# This show the various system images to the user
+do_menu_view_images() {
+  do_view_images
   do_prompt
   return 0
 }
@@ -430,7 +484,7 @@ do_network_download() {
   esac
 
   # set local network parameters
-  do_set_local_ip || return 1
+  [ -z "$NET_OK" ] && ! do_set_local_ip && return 1
 
   if [ "$mode" != "$NET_REMOTE_MODE" ];then
     NET_REMOTE_MODE=$mode
@@ -440,12 +494,12 @@ do_network_download() {
   if [ "$mode" = "HTTP" -o "$mode" = "FTP" ]; then
     do_ask_bool "Use a proxy server" NET_PROX || return 1
     if [ "$NET_PROX" = "Y" ]; then
-      do_ask_ip_address "Enter proxy server IP address" NET_PROX_HOST || return 1
+      do_ask_non_void_ip_address "Enter proxy server IP address" NET_PROX_HOST || return 1
       do_ask_int "Enter proxy server port" NET_PROX_PORT 1 65535 || return 1
     fi
   fi
 
-  do_ask_ip_address "Enter $mode server IP address" NET_REMOTE_HOST || return 1
+  do_ask_non_void_ip_address "Enter $mode server IP address" NET_REMOTE_HOST || return 1
   do_ask_int "Enter $mode server port" NET_REMOTE_PORT 1 65535 || return 1
 
   if [ "$mode" != "RAW" ]; then
@@ -509,24 +563,28 @@ do_network_download() {
 # Generic function to load an image, can be both from serial port or network.
 do_menu_download_image() {
   do_menu "Download image|Download from serial port|Download from an HTTP server|Download from an FTP server|Download from a TFTP server|Download from a RAW TCP server"
+  err=1
   case $LINE in
-    1) do_serial_download       && return 0 ;;
-    2) do_network_download HTTP && return 0 ;;
-    3) do_network_download FTP  && return 0 ;;
-    4) do_network_download TFTP && return 0 ;;
-    5) do_network_download RAW  && return 0 ;;
+    1) do_serial_download       ; err=$? ;;
+    2) do_network_download HTTP ; err=$? ;;
+    3) do_network_download FTP  ; err=$? ;;
+    4) do_network_download TFTP ; err=$? ;;
+    5) do_network_download RAW  ; err=$? ;;
   esac
-  return 1
+  [ $err = 0 ] && do_inform "Do not forget to save this image."
+  return $?
 }
 
 # checks if the recently downloaded flash image is valid, then saves it if the
 # user wants to do so. Saving involves several external commands :
 # - update-boot-image [-d flash_part] image
 
-#### FIXME !!! THIS IS INCOMPLETE #####
-
 do_check_and_save_image() {
-  do_inform "Checking the image..."
+  if [ ! -s $DOWNLOAD_IMAGE_FILE ]; then
+    do_inform "No pending image. Please download an image first."
+    do_menu_download_image || return 1
+  fi
+  do_inform "Checking pending image..."
   update-boot-image -n -q $DOWNLOAD_IMAGE_FILE
   err=$?
   do_inform
@@ -535,7 +593,7 @@ do_check_and_save_image() {
     2) do_prompt "This image is invalid ! Please try another image." ; return 1 ;;
     *) do_prompt "Internal error. Please retry, reboot then report." ; return 1 ;;
   esac
-  do_inform "Please wait one minute while writing to flash..."
+  do_inform "Please wait for write completion. This can take one minute..."
   update-boot-image -q $DOWNLOAD_IMAGE_FILE
   err=$?
   do_inform
@@ -551,7 +609,7 @@ do_check_and_save_image() {
   if [ $err = 5 ]; then
     do_error "Failed to save the image. I need to delete the current image."
     do_confirm "The system will be unusable until successful save" || return 0
-    do_inform "Please wait one minute while writing to flash..."
+    do_inform "Please wait for write completion. This can take one minute..."
     if ! update-boot-image -f -q $DOWNLOAD_IMAGE_FILE -d $FLASH_PART; then
       do_inform
       do_error "Failed to save the image. You may have to reformat the partition."
@@ -565,23 +623,135 @@ do_check_and_save_image() {
   return 0
 }
 
+
+# boots an image
+do_menu_boot_image() {
+  do_view_images
+
+  while do_menu "Boot image|Boot pending image|Boot active image|Boot backup image"; do
+    if [ $LINE = 1 ]; then
+      if [ ! -s $DOWNLOAD_IMAGE_FILE ]; then
+        do_inform "No pending image. Please download an image first."
+        do_inform
+        do_menu_download_image || return 1
+      fi
+      do_inform "Checking pending image..."
+      _dir=$(update-boot-image -n -q -k $DOWNLOAD_IMAGE_FILE)
+      err=$?
+      do_inform
+      if [ $err = 2 ]; then
+        do_error "This image is invalid ! Please try another image."
+	rm -rf $_dir
+        continue;
+      elif [ $err != 0 ]; then
+        do_prompt "Internal error. Please retry, reboot then report." 
+	rm -rf $_dir
+        return 1
+      fi
+      if ! do_confirm "Image is valid. Ready to boot this image"; then
+	rm -rf $_dir
+	return 0
+      fi
+      # files have been kept in $_dir.
+      do_inform "Loading image in memory..."
+      if ! kexec -l --command-line="$(cat $_dir/*/kernel.arg) flash=${FLASH_PART##*/}" \
+           --initrd="$(echo $_dir/*/initrd.img)" $_dir/*/kernel.img; then
+        do_error "Failed to load image"
+      else
+        do_inform "Booting image now..."
+        kexec -e -x
+        do_error "Boot failed"
+      fi
+      kexec -u >/dev/null 2>&1
+      rm -rf $_dir
+      do_prompt
+      return 1
+    else
+      flash="$FLASH_PART"
+      umount $FLASH_MNT >/dev/null 2>&1 || mkdir -p $FLASH_MNT >/dev/null 2>&1
+      mount -r $flash $FLASH_MNT >/dev/null 2>&1
+      if [ $LINE = 2 ]; then     ### active image
+        do_inform "Loading active image in memory..."
+        kexec -l --command-line="$(cat $FLASH_MNT/sys/active/kernel.arg) flash=${FLASH_PART##*/}" --initrd="$(echo $FLASH_MNT/sys/active/initrd.img)" $FLASH_MNT/sys/active/kernel.img
+	err=$?
+        # fake current boot to "active(retry)"
+        grub-mbr-default -q $FLASH_MBR 2
+      else
+        do_inform "Loading backup image in memory..."
+        kexec -l --command-line="$(cat $FLASH_MNT/sys/backup/kernel.arg) flash=${FLASH_PART##*/}" --initrd="$(echo $FLASH_MNT/sys/backup/initrd.img)" $FLASH_MNT/sys/backup/kernel.img
+	err=$?
+        # fake current boot as "backup(retry)"
+        grub-mbr-default -q $FLASH_MBR 4
+      fi
+      umount $FLASH_MNT >/dev/null 2>&1
+      if [ $err -gt 0 ]; then
+        do_error "Failed to load image"
+      else
+        if ! do_confirm "Image is valid. Ready to boot this image"; then
+          kexec -u >/dev/null 2>&1
+          rm -rf $_dir
+          return 0
+        fi
+        do_inform "Booting image now..."
+        kexec -e -x
+        do_error "Boot failed"
+      fi
+      kexec -u >/dev/null 2>&1
+      rm -rf $_dir
+      do_prompt
+      return 1
+    fi
+  done
+
+  return 0
+}
+
+
+# boots an image
+do_menu_change_default_image() {
+  do_view_images
+
+  _cur=$(grub-mbr-default -q $FLASH_MBR)
+  case $_cur in
+    0|1) do_inform "Next boot will use ACTIVE image" ;;
+    2|3) do_inform "Next boot will use BACKUP image" ;;
+    *)   do_inform "Next boot will stop on firmware" ;;
+  esac
+
+  if do_menu "Default boot|Use active image for next boot|Use backup image for next boot"; then
+    if [ $LINE = 1 ]; then
+      # set next boot to "active"
+      grub-mbr-default -q $FLASH_MBR 0
+      do_inform "Next boot will use ACTIVE image"
+    else
+      # set next boot to "active"
+      grub-mbr-default -q $FLASH_MBR 2
+      do_inform "Next boot will use BACKUP image"
+    fi
+  fi
+
+  return 0
+}
+
 # main menu which never returns.
 do_menu_main() {
   while : ; do
-    while do_menu "Main menu|Select system partition ($FLASH_PART = $FLASH_SIZE kB)|View images|Download image|Boot an image|Change default image|Delete image|Change default config|Delete config|Shell|Format system partition|Reboot|Exit(dangerous)"; do
+    while do_menu "Main menu|Select system partition ($FLASH_PART = $FLASH_SIZE kB)|View images|Network setup|Download image|Save image|Change default image|Boot an image|Delete image|Change default config|Delete config|Shell|Format system partition|Reboot|Exit(dangerous)"; do
       case $LINE in
         1) do_select_flash ;;
         2) do_menu_view_images ;;
-        3) do_menu_download_image && do_check_and_save_image ;;
-        4) do_menu_boot_image ;;
-        5) do_menu_change_default_image ;;
-        6) do_menu_delete_image ;;
-        7) do_menu_change_default_config ;;
-        8) do_menu_delete_config ;;
-        9) do_inform "Type 'exit' to leave this shell.";/bin/sh ;;
-        10) do_menu_format_flash ;;
-        11) do_confirm "Ready to REBOOT" && reboot ;;
-        12) exit 0 ;;
+        3) do_set_local_ip ;;
+        4) do_menu_download_image ;;
+        5) do_check_and_save_image ;;
+        6) do_menu_change_default_image ;;
+        7) do_menu_boot_image ;;
+        8) do_menu_delete_image ;;
+        9) do_menu_change_default_config ;;
+        10) do_menu_delete_config ;;
+        11) do_inform "Type 'exit' to leave this shell.";/bin/sh ;;
+        12) do_menu_format_flash ;;
+        13) do_confirm "Ready to REBOOT" && reboot ;;
+        14) exit 0 ;;
       esac
     done
     #echo "No default menu"
@@ -607,6 +777,7 @@ init_flash_from_cmdline() {
 #  get_partition_size $FLASH_PART
 #  FLASH_SIZE=$REPLY
   if ! do_test_system_partition >/dev/null 2>&1; then
+    FLASH_MBR=""
     FLASH_PART=""
     FLASH_SIZE=0
     FIRMWARE_PART=""
