bootstrap: updated update-boot-image to fix a few error messages

diff --git a/rootfs/scripts/update-boot-image b/rootfs/scripts/update-boot-image
--- a/rootfs/scripts/update-boot-image
+++ b/rootfs/scripts/update-boot-image
@@ -1,12 +1,15 @@
 #!/bin/sh
 
+## update-boot-image 20070102
 ## Usage :
-##   $ update-boot-image [-k] [-h] [-n] [-q] [-f] [-v] [-m mntdir] [-d device] $DIR/image.tgz
+##   $ update-boot-image [-k] [-h] [-n] [-q] [-f] [-v] [-m mntdir] [-d device]
+##                       [-b mbrlist] $DIR/image.tgz
 ##     -h : show this help
 ##     -n : just check the image and do not change anything
 ##     -q : be quiet
 ##     -f : force removal of both old images if required and ignore model name
 ##     -d : use this flash device if not mounted yet
+##     -b : use comma-separated list of MBR devices
 ##     -v : show a valid image version even in quiet mode
 ##     -m : use the pre-mounted flash FS <mntdir>
 ##     -k : keep the temporary files and output the directory name.
@@ -22,8 +25,10 @@
 ##    5 : not enough space on flash, but removable dirs exist
 ## 
 #
-# This script needs :
-# grep, cut, mount, umount, grub-mbr-default in its PATH, /proc mounted, and flash unmounted.
+# This script needs : tr, grep, cut, mount, umount, grub-mbr-default in its
+#                     PATH, /proc mounted, and flash unmounted.
+# WARNING! This script needs to be able to run under busybox, so please limit
+# the fantasy !
 
 PATH=/usr/sbin:/usr/bin:/sbin:/bin
 export PATH
@@ -38,6 +43,7 @@ MOUNTED_RO=
 SHOW_VERSION=
 KEEP_FILES=
 MODEL=
+MBRLIST=
 
 while [ $# -gt 0 ]; do
   [ -z "${1##-*}" ] || break
@@ -51,6 +57,9 @@ while [ $# -gt 0 ]; do
     shift
   elif [ ".$1" = ".-m" ]; then
     FLASHDIR="$2"
+    shift
+  elif [ ".$1" = ".-b" ]; then
+    MBRLIST="$( echo $2 | tr ',' ' ')"
     shift
   else
     if [ ".$1" = ".-h" ]; then
@@ -120,7 +129,7 @@ if [ ! -r "$FILE" ]; then
   do_exit_error 1
 fi
 
-(cd $TEMP && tar zxf - >/dev/null 2>&1) < $FILE
+(cd $TEMP 2>/dev/null && tar zxf - >/dev/null 2>&1) < $FILE
 # we don't check the return code because gzip can return false errors
 # because of additionnal bytes resulting from various upload methods.
 # The md5 is the only valid test.
@@ -130,13 +139,13 @@ fi
 #  do_exit_error 2
 #fi
 
-if ! (cd $TEMP/* ; md5sum -c system.sig >/dev/null 2>&1); then
+if ! (cd $TEMP/* && md5sum -c system.sig) >/dev/null 2>&1; then
   [ -z "$QUIET" ] && echo "Corrupted image."
   do_exit_error 2
 fi
 
+IMGVER=$(cat $TEMP/*/system.ver 2>/dev/null || cat $TEMP/*/kernel.ver 2>/dev/null)
 if [ -n "$SHOW_VERSION" ]; then
-  IMGVER=$(cat $TEMP/*/system.ver || cat $TEMP/*/kernel.ver 2>/dev/null)
   [ -n "$IMGVER" ] && echo "$IMGVER" || echo "unknown"
 fi
 
@@ -145,7 +154,8 @@ fi
 set -- $(grep "^Model:" /usr/share/factory/version 2>/dev/null)
 MODEL="$2"
 if [ -z "$FORCE" -a \
-     -n "$MODEL" -a -n "$IMGVER" -a -n "${IMGVER##*-$MODEL-*}" ]; then
+     -n "$MODEL" -a -n "$IMGVER" -a \
+     -n "${IMGVER##*-$MODEL-*}" -a -n "${IMGVER##*$MODEL-*}" ]; then
   [ -z "$QUIET" ] && echo "Wrong image for model $MODEL."
   do_exit_error 2
 fi
@@ -175,7 +185,7 @@ if [ -n "$MOUNTED_RO" ]; then
 fi
 
 if [ -n "$MOUNTED" ] && ! mount -wo remount $FLASHDIR >/dev/null 2>&1 || \
-  ! mount $FLASH $FLASHDIR >/dev/null 2>&1; then
+  ! mount -n $FLASH $FLASHDIR >/dev/null 2>&1; then
   [ -z "$QUIET" ] && echo "Cannot mount flash."
   do_exit_error 3
 else
@@ -251,23 +261,49 @@ if ( [ -n "$MOUNTED_RO" ] && mount -ro remount $FLASHDIR || umount $FLASHDIR ) >
   MOUNTED=0
 fi
 
-flashnum=${FLASH##*[^0-9]}
-mbr=${FLASH%$flashnum}
-mbrdev=${mbr##/dev/}
-while [ -n "$mbrdev" ] && ! grep -q " $mbrdev\$" /proc/partitions; do
-  mbrdev=${mbrdev%?}
-done
+if [ -z "$MBRLIST" ]; then
+  mbr="$(cat /proc/cmdline)"
+  if [ -z "${mbr##*mbr=*}" ]; then
+    # mbr specified in /proc/cmdline. It may be a comma-separated list.
+    mbr=${mbr##*mbr=}
+    mbr=${mbr%% *} ; mbr="$(echo $mbr | tr ',' ' ')"
+    for mbrdev in $mbr; do
+      mbrdev=${mbrdev##/dev/}
+      [ -n "$mbrdev" ] || continue
+      MBRLIST="$MBRLIST $mbrdev"
+    done
+  fi
+fi
 
-if [ -z "$mbrdev" ]; then
-  [ -z "$QUIET" ] && echo "MBR not found."
+if [ -z "$MBRLIST" ]; then
+  flashnum=${FLASH##*[^0-9]}
+  mbr=${FLASH%$flashnum}
+  mbrdev=${mbr##/dev/}
+  while [ -n "$mbrdev" ] && ! grep -q "$mbrdev\( .*\)\?\$" /proc/partitions; do
+    mbrdev=${mbrdev%?}
+  done
+  [ -n "$mbrdev" ] && MBRLIST="$MBRLIST $mbrdev"
+fi
+
+if [ -z "$MBRLIST" ]; then
+  if [ -z "$QUIET" ]; then
+    echo "FATAL: MBR not found."
+    echo "Please check the 'mbr' parameter on kernel command line."
+  fi
   do_exit_error 3
 fi
                      
-# activate first boot image
-if ! grub-mbr-default ${QUIET:+-q} /dev/$mbrdev 0; then
-  [ -z "$QUIET" ] && echo "Cannot change active image."
-  do_exit_error 4
-fi
+# activate first boot image on each MBR
+err=
+for mbrdev in $MBRLIST; do
+  [ -n "${mbrdev##/*}" ] && mbrdev="/dev/$mbrdev"
+  [ -z "$QUIET" ] && echo "Updating MBR device $mbrdev ..."
+  if ! grub-mbr-default ${QUIET:+-q} $mbrdev 0; then
+    [ -z "$QUIET" ] && echo "Cannot change active image."
+    err=1
+  fi
+done
+[ -z "$err" ] || do_exit_error 4
 
 [ -z "$QUIET" ] && echo "Active image updated."
 do_exit_ok
