bootstrap: update-boot-image: automatically choose the image to replace
- automatic selection of image to be replaced
- we now try our best to keep the running image untouched and only
  replace the other one
- several methods are used to find what image is the current one
- if the running image is none of those on the flash, we try to
  detect if we're replacing one of the existing images
- by default, image 1 is used when no image is found
- all error situations have been tested, including a full FS.

diff --git a/rootfs/scripts/update-boot-image b/rootfs/scripts/update-boot-image
--- a/rootfs/scripts/update-boot-image
+++ b/rootfs/scripts/update-boot-image
@@ -1,12 +1,11 @@
 #!/bin/sh
 
-## update-boot-image 20081124
+## update-boot-image 20081229
 ## Usage :
 ##   $ update-boot-image [-k] [-h] [-n] [-q] [-f] [-v] [-m mntdir] [-d device]
-##                       [-b mbrlist] $DIR/image.tgz
-##     -h : show this help
+##                       [-b mbrlist] [-1|-2] $DIR/image.tgz
+##     -h : show this help      -q : be quiet
 ##     -n : just check the image and do not change anything
-##     -q : be quiet
 ##     -f : force removal of both old images if required and ignore model name
 ##     -d : use this flash device if not mounted yet
 ##     -b : use comma-separated list of MBR devices
@@ -15,6 +14,7 @@
 ##     -k : keep the temporary files and output the directory name.
 ##   Use -n -q -v to get the image version only.
 ##       -n -q -k to extract the image and get access to the files.
+##     -1, -2 : force installation of image 1 / image 2
 ## 
 ## Return codes :
 ##    0 : everything OK
@@ -47,6 +47,12 @@ KEEP_FILES=
 MODEL=
 MBRLIST=
 
+# automatic detection of the image to remove (active/backup)
+# IMG_DELETE and IMG_KEEP may be a list
+IMG_DELETE=
+IMG_INSTALL=
+IMG_KEEP=
+
 while [ $# -gt 0 ]; do
   [ ".$1" = ".-" ] && break
   [ -z "${1##-*}" ] || break
@@ -55,6 +61,14 @@ while [ $# -gt 0 ]; do
   elif [ ".$1" = ".-q" ]; then QUIET=1
   elif [ ".$1" = ".-v" ]; then SHOW_VERSION=1
   elif [ ".$1" = ".-k" ]; then KEEP_FILES=1
+  elif [ ".$1" = ".-1" ]; then
+    IMG_DELETE="active"
+    IMG_INSTALL="active"
+    IMG_KEEP="backup"
+  elif [ ".$1" = ".-2" ]; then
+    IMG_DELETE="backup"
+    IMG_INSTALL="backup"
+    IMG_KEEP="active"
   elif [ ".$1" = ".-d" ]; then
     FLASH="$2"
     shift
@@ -143,6 +157,17 @@ find_flash() {
   return 0
 }
 
+# return in REPLY the value of the first occurrence of variable $1
+get_from_cmdline() {
+    REPLY="$(cat /proc/cmdline)"
+    if [ -n "${REPLY##*[   ]$1=*}" ]; then
+	REPLY=
+	return 1
+    fi
+    REPLY="${REPLY##*[  ]$1=}"
+    REPLY="${REPLY%% *}"
+}
+
 while [ $seq -lt 1000 ] && ! mkdir "$TEMP" >/dev/null 2>&1; do
   seq=$(($seq+1))
   TEMP="/tmp/temp-$$_$seq"
@@ -229,24 +254,68 @@ else
   MOUNTED=1
 fi
 
+if [ -z "$IMG_INSTALL" ]; then
+    if get_from_cmdline img; then
+	if [ "$REPLY" = "active" ]; then
+	    IMG_KEEP="active"
+	    IMG_DELETE="backup"
+	    IMG_INSTALL="backup"
+	elif [ "$REPLY" = "backup" ]; then
+	    IMG_KEEP="backup"
+	    IMG_DELETE="active"
+	    IMG_INSTALL="active"
+	fi
+    fi
+    if [ -z "$IMG_INSTALL" ]; then
+	# we have to guess. We first replace the missing image if any. Then we
+	# replace the active image if current version is the same as the backup
+	# or if we're re-installing the same version as the active image.
+	# Otherwise we replace the backup image.
+	cur_ver="$(readlink /usr/share/factory/version)"
+	if [ ! -s "$FLASHDIR/sys/active/system.ver" ]; then
+	    IMG_KEEP="backup"
+	    IMG_INSTALL="active"
+	    IMG_DELETE="active"
+	elif [ ! -s "$FLASHDIR/sys/backup/system.ver" ]; then
+	    IMG_KEEP="active"
+	    IMG_INSTALL="backup"
+	    IMG_DELETE="backup"
+	elif [ -n "$cur_ver" -a \
+	    "$cur_ver" = "$(cat $FLASHDIR/sys/backup/system.ver 2>&1)" ]; then
+	    IMG_KEEP="backup"
+	    IMG_INSTALL="active"
+	    IMG_DELETE="active"
+	elif [ "$IMGVER" = "$(cat $FLASHDIR/sys/active/system.ver 2>&1)" ]; then
+	    IMG_KEEP="backup"
+	    IMG_INSTALL="active"
+	    IMG_DELETE="active"
+	else
+	    # if everything else fails, assume we're running on the active image
+	    IMG_KEEP="active"
+	    IMG_INSTALL="backup"
+	    IMG_DELETE="backup"
+	fi
+    fi
+fi
+
 rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
 if mv $TEMP/* $FLASHDIR/sys/tmp >/dev/null 2>&1; then
   if [ -e "$FLASHDIR/sys/active" -a -e "$FLASHDIR/sys/backup" ]; then
-    if ! rm -rf "$FLASHDIR/sys/backup" >/dev/null 2>&1; then
-      rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
-      [ -z "$QUIET" ] && echo "Cannot remove old image."
-      do_exit_error 4
-    fi
+    for old in $IMG_DELETE; do
+	if ! rm -rf "$FLASHDIR/sys/$old" >/dev/null 2>&1; then
+	    rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
+	    [ -z "$QUIET" ] && echo "Cannot remove old image."
+	    do_exit_error 4
+	fi
+    done
   fi
-  if ( [ -e "$FLASHDIR/sys/active" ] && \
-     ! mv "$FLASHDIR/sys/active" "$FLASHDIR/sys/backup" >/dev/null 2>&1) || \
-     ! mv "$FLASHDIR/sys/tmp" "$FLASHDIR/sys/active" >/dev/null 2>&1; then
+  if ! mv "$FLASHDIR/sys/tmp" "$FLASHDIR/sys/$IMG_INSTALL" >/dev/null 2>&1; then
     rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
     [ -z "$QUIET" ] && echo "Cannot install new image."
     do_exit_error 4
   fi
 else
-  # mv failed. The tmp dir might contain incomplete files.
+  # mv failed. Try to find some space. The tmp dir might contain incomplete files.
   rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
   if [ ! -e "$FLASHDIR/sys/active" -a ! -e "$FLASHDIR/sys/backup" ]; then
     rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
@@ -255,11 +324,13 @@ else
   fi
 
   if [ -e "$FLASHDIR/sys/active" -a -e "$FLASHDIR/sys/backup" ]; then
-    if ! rm -rf "$FLASHDIR/sys/backup" >/dev/null 2>&1; then
-      rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
-      [ -z "$QUIET" ] && echo "Cannot remove old image."
-      do_exit_error 4
-    fi
+    for old in $IMG_DELETE; do
+	if ! rm -rf "$FLASHDIR/sys/$old" >/dev/null 2>&1; then
+	    rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
+	    [ -z "$QUIET" ] && echo "Cannot remove old image."
+	    do_exit_error 4
+	fi
+    done
   fi
 
   if mv $TEMP/* $FLASHDIR/sys/tmp >/dev/null 2>&1 ; then
@@ -267,29 +338,38 @@ else
       rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
       [ -z "$QUIET" ] && echo "Try to reformat flash."
       do_exit_error 4
-    elif ( [ -e "$FLASHDIR/sys/active" ] && \
-      ! mv "$FLASHDIR/sys/active" "$FLASHDIR/sys/backup" ) || \
-      ! mv "$FLASHDIR/sys/tmp" "$FLASHDIR/sys/active"; then
-      rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
-      [ -z "$QUIET" ] && echo "Cannot install new image."
-      do_exit_error 4
+    elif ! mv "$FLASHDIR/sys/tmp" "$FLASHDIR/sys/$IMG_INSTALL" >/dev/null 2>&1; then
+	rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
+	[ -z "$QUIET" ] && echo "Cannot install new image."
+	do_exit_error 4
     fi
   else
+    rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
     if [ -z "$FORCE" ]; then
       [ -z "$QUIET" ] && echo "Need to remove all images."
       do_exit_error 5
     fi
 
-    if ! rm -rf "$FLASHDIR/sys/active" "$FLASHDIR/sys/backup" >/dev/null 2>&1; then
-      [ -z "$QUIET" ] && echo "Cannot remove all images."
-      rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
-      do_exit_error 4
-    fi
+    IMG_DELETE="$IMG_DELETE $IMG_KEEP"
+    IMG_KEEP=
+    for old in $IMG_DELETE; do
+	if ! rm -rf "$FLASHDIR/sys/$old" >/dev/null 2>&1; then
+	    rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
+	    [ -z "$QUIET" ] && echo "Cannot remove all images."
+	    do_exit_error 4
+	fi
+    done
 
-    if mv $TEMP/* $FLASHDIR/sys/tmp >/dev/null 2>&1 ; then
+    if ! mv $TEMP/* $FLASHDIR/sys/tmp >/dev/null 2>&1 ; then
       rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
       [ -z "$QUIET" ] && echo "Try to reformat flash."
       do_exit_error 4
+    fi
+
+    if ! mv "$FLASHDIR/sys/tmp" "$FLASHDIR/sys/$IMG_INSTALL" >/dev/null 2>&1; then
+	rm -rf $FLASHDIR/sys/tmp >/dev/null 2>&1
+	[ -z "$QUIET" ] && echo "Cannot install new image."
+	do_exit_error 4
     fi
   fi
 fi
@@ -337,11 +417,17 @@ if [ -z "$MBRLIST" ]; then
 fi
                      
 # activate first boot image on each MBR
+if [ "$IMG_INSTALL" = "backup" ]; then
+    img_num=2
+else
+    img_num=0
+fi
+
 err=
 for mbrdev in $MBRLIST; do
   [ -n "${mbrdev##/*}" ] && mbrdev="/dev/$mbrdev"
   [ -z "$QUIET" ] && echo "Updating MBR device $mbrdev ..."
-  if ! grub-mbr-default ${QUIET:+-q} $mbrdev 0; then
+  if ! grub-mbr-default ${QUIET:+-q} $mbrdev $img_num; then
     [ -z "$QUIET" ] && echo "Cannot change active image."
     err=1
   fi
